import OpenAI from "openai";

const CODEX_MODEL = "o4-mini";

export interface CodexRequest {
  systemPrompt: string;
  userMessage: string;
  accessToken: string;
}

export interface CodexResponse {
  success: boolean;
  result: string;
  model: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

export async function callCodex(request: CodexRequest): Promise<CodexResponse> {
  const client = new OpenAI({
    apiKey: request.accessToken,
  });

  try {
    const completion = await client.chat.completions.create({
      model: CODEX_MODEL,
      messages: [
        { role: "system", content: request.systemPrompt },
        { role: "user", content: request.userMessage },
      ],
    });

    const content = completion.choices[0]?.message?.content;
    if (!content) {
      return {
        success: false,
        result: "No response generated by the model.",
        model: CODEX_MODEL,
      };
    }

    return {
      success: true,
      result: content,
      model: CODEX_MODEL,
      usage: completion.usage
        ? {
            promptTokens: completion.usage.prompt_tokens,
            completionTokens: completion.usage.completion_tokens,
            totalTokens: completion.usage.total_tokens,
          }
        : undefined,
    };
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Unknown error occurred";
    return {
      success: false,
      result: `Codex API error: ${message}`,
      model: CODEX_MODEL,
    };
  }
}
